import {
  Document,
  Font,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";
import React from "react";

Font.register({
  family: "Inter",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2",
      fontWeight: 400,
    },
    {
      src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hiA.woff2",
      fontWeight: 700,
    },
  ],
});

export const baseStyles = StyleSheet.create({
  page: {
    fontFamily: "Inter",
    fontSize: 10,
    color: "#1e293b",
    paddingTop: 40,
    paddingBottom: 60,
    paddingHorizontal: 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingBottom: 8,
    marginBottom: 20,
  },
  logo: {
    fontSize: 16,
    fontWeight: 700,
    color: "#0f172a",
  },
  headerMeta: {
    fontSize: 8,
    color: "#64748b",
    textAlign: "right",
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 6,
  },
  footerText: {
    fontSize: 7,
    color: "#94a3b8",
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#0f172a",
    marginBottom: 8,
  },
  row: {
    flexDirection: "row",
    gap: 8,
  },
  cell: {
    flex: 1,
  },
  label: {
    fontSize: 7,
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  value: {
    fontSize: 10,
    color: "#1e293b",
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    marginVertical: 12,
  },
  table: {
    width: "100%",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f8fafc",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  tableHeaderCell: {
    flex: 1,
    fontSize: 7,
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  tableCell: {
    flex: 1,
    fontSize: 9,
    color: "#1e293b",
  },
});

interface BaseDocumentProps {
  workspaceName: string;
  documentId: string;
  children: React.ReactNode;
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

interface PageNumberProps {
  pageNumber?: number;
  totalPages?: number;
}

function FooterContent({ documentId }: { documentId: string }) {
  return (
    <View style={baseStyles.footer} fixed>
      <Text style={baseStyles.footerText}>
        Generated by MeasureDeck | Document ID: {documentId}
      </Text>
      <Text
        style={baseStyles.footerText}
        render={({ pageNumber, totalPages }: PageNumberProps) =>
          `Page ${pageNumber ?? 1} of ${totalPages ?? 1}`
        }
      />
    </View>
  );
}

export function BaseDocument({ workspaceName, documentId, children }: BaseDocumentProps) {
  const today = formatDate(new Date());

  return (
    <Document>
      <Page size="A4" style={baseStyles.page}>
        <View style={baseStyles.header} fixed>
          <Text style={baseStyles.logo}>MeasureDeck</Text>
          <View>
            <Text style={baseStyles.headerMeta}>{workspaceName}</Text>
            <Text style={baseStyles.headerMeta}>{today}</Text>
          </View>
        </View>

        {children}

        <FooterContent documentId={documentId} />
      </Page>
    </Document>
  );
}

export default BaseDocument;
