"use client";

import { useState } from "react";
import { Search, Download } from "lucide-react";
import { formatDate, cn } from "@/lib/utils";

const REPORTS = [
  { id: "r1", name: "May Monthly Summary", project: "Phase 1 - Foundation Works", workspace: "Apex Construction Ltd", type: "Monthly", generated_by: "James Thornton", status: "published", created_at: "2026-05-31" },
  { id: "r2", name: "Office Refurb Progress Report", project: "Office Block Refurbishment", workspace: "Meridian Contractors", type: "Progress", generated_by: "Priya Nair", status: "draft", created_at: "2026-06-08" },
  { id: "r3", name: "CVR Summary Q1 2026", project: "Phase 1 - Foundation Works", workspace: "Apex Construction Ltd", type: "CVR", generated_by: "James Thornton", status: "published", created_at: "2026-04-01" },
  { id: "r4", name: "Drainage Site B Completion", project: "Drainage Upgrade - Site B", workspace: "BuildRight Group", type: "Completion", generated_by: "Oliver Reed", status: "published", created_at: "2024-12-15" },
  { id: "r5", name: "Demo Report Sample", project: "Demo Site Project", workspace: "Demo Workspace", type: "Monthly", generated_by: "Demo User", status: "draft", created_at: "2026-06-01" },
];

const STATUS_CHIP: Record<string, string> = { published: "chip-success", draft: "chip-muted" };
const TYPE_CHIP: Record<string, string> = { Monthly: "chip-info", Progress: "chip-warning", CVR: "chip-success", Completion: "chip-info" };

export default function AdminReportsPage() {
  const [search, setSearch] = useState("");

  const filtered = REPORTS.filter((r) => {
    const q = search.toLowerCase();
    return !q || r.name.toLowerCase().includes(q) || r.workspace.toLowerCase().includes(q);
  });

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 style={{ fontSize: 22, fontWeight: 700 }}>Reports</h1>
          <p style={{ fontSize: 13, color: "var(--text-muted)", marginTop: 2 }}>{REPORTS.length} reports across all workspaces</p>
        </div>
        <button className="btn btn-secondary btn-sm" onClick={() => alert("Exporting…")}><Download size={14} /> Export</button>
      </div>

      <div className="page-content">
        <div style={{ position: "relative", maxWidth: 360, marginBottom: 16 }}>
          <Search size={14} style={{ position: "absolute", left: 10, top: "50%", transform: "translateY(-50%)", color: "var(--text-muted)" }} />
          <input className="form-input" style={{ paddingLeft: 32 }} placeholder="Search reports…" value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>

        <div className="card" style={{ overflow: "hidden" }}>
          <table className="data-table">
            <thead>
              <tr><th>Name</th><th>Project</th><th>Workspace</th><th>Type</th><th>Generated By</th><th>Status</th><th>Created</th></tr>
            </thead>
            <tbody>
              {filtered.map((r) => (
                <tr key={r.id}>
                  <td style={{ fontWeight: 500, fontSize: 13 }}>{r.name}</td>
                  <td style={{ fontSize: 12, color: "var(--text-muted)" }}>{r.project}</td>
                  <td style={{ fontSize: 12, color: "var(--text-muted)" }}>{r.workspace}</td>
                  <td><span className={cn("badge", TYPE_CHIP[r.type] ?? "chip-info")}>{r.type}</span></td>
                  <td style={{ fontSize: 13 }}>{r.generated_by}</td>
                  <td><span className={cn("badge", STATUS_CHIP[r.status] ?? "chip-muted")}>{r.status}</span></td>
                  <td style={{ fontSize: 12, color: "var(--text-muted)" }}>{formatDate(r.created_at)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
